name: ecommerse_store
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

#-----------------------------pacakeges---------------#
dependencies:
  flutter:
    sdk: flutter

#------------utility Packeges----------_#
#  Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2


  #-----------------State Management-------------------#
  get: ^4.6.5



  #--------Product Specifices------------

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
#-----------Local Assets----------------------#
  assets:
    - assets/fonts/
    - assets/icons/brands/
    - assets/images/
    - assets/logo/

#----------------------Local Fonts------------#
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_black.ttf
          weight: 300
        - asset: assets/fonts/avenir_regular.ttf
          weight: 200


